#!/usr/bin/env bash
#
# sync-skills.sh — vendor this repo's canonical Firetiger skills into a consumer
# plugin's expected layout.
#
# Skills are authored ONCE in this repo (one top-level directory per skill, each
# holding a SKILL.md and optional references/). This script copies them verbatim
# into a target plugin checkout and applies a per-host transform:
#
#   --host cursor   skills -> <target>/skills/           (cursor-plugin: plugin.json "skills": "skills")
#   --host claude   skills -> <target>/skills/           (claude-plugin: plugins support skills/)
#                   plus thin <target>/commands/<name>.md slash-command wrappers
#                   that just invoke the corresponding skill.
#
# It also stamps the vendored copy with the source tag + content hash
# (<target>/skills/.firetiger-skills-source) and installs a drift-check workflow
# so a hand-edited vendored copy can't silently diverge from canonical.
#
# Usage:
#   sync-skills.sh --host <cursor|claude> --target <dir> [--tag <tag>] [--source <dir>]
#
# Run it locally against a checkout of a plugin to test, e.g.:
#   scripts/sync-skills.sh --host cursor --target ../cursor-plugin --tag v1.2.3
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE_REPO="firetiger-oss/skills"
STAMP_NAME=".firetiger-skills-source"
GEN_MARKER="Generated by scripts/sync-skills.sh from ${SOURCE_REPO}"

HOST=""
TARGET=""
TAG=""

die() { echo "sync-skills.sh: $*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --host)   HOST="${2:?}"; shift 2 ;;
    --target) TARGET="${2:?}"; shift 2 ;;
    --tag)    TAG="${2:?}"; shift 2 ;;
    --source) SOURCE_DIR="$(cd "${2:?}" && pwd)"; shift 2 ;;
    -h|--help)
      sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[ -n "$HOST" ]   || die "missing --host <cursor|claude>"
[ -n "$TARGET" ] || die "missing --target <dir>"
case "$HOST" in cursor|claude) ;; *) die "invalid --host: $HOST (want cursor|claude)" ;; esac
[ -d "$TARGET" ] || die "target is not a directory: $TARGET"
TARGET="$(cd "$TARGET" && pwd)"

# Default the tag to whatever git can tell us about the source checkout.
if [ -z "$TAG" ]; then
  TAG="$(git -C "$SOURCE_DIR" describe --tags --always --dirty 2>/dev/null || echo dev)"
fi

# Discover canonical skill directories (top-level dirs holding a SKILL.md).
# (Plain while-read loop for bash 3.2 portability — no mapfile.)
SKILL_DIRS=()
while IFS= read -r _dir; do
  [ -n "$_dir" ] && SKILL_DIRS+=("$_dir")
done < <(
  find "$SOURCE_DIR" -mindepth 2 -maxdepth 2 -name SKILL.md -type f \
    | sed "s|/SKILL.md$||" | LC_ALL=C sort
)
[ "${#SKILL_DIRS[@]}" -gt 0 ] || die "no canonical skills (dirs with SKILL.md) found under $SOURCE_DIR"

echo "Syncing ${#SKILL_DIRS[@]} skill(s) from ${SOURCE_REPO}@${TAG} -> ${TARGET} (host: ${HOST})"

# ---------------------------------------------------------------------------
# 1. Vendor the skills: wipe and repopulate <target>/skills/ verbatim.
# ---------------------------------------------------------------------------
SKILLS_OUT="$TARGET/skills"
rm -rf "$SKILLS_OUT"
mkdir -p "$SKILLS_OUT"

for dir in "${SKILL_DIRS[@]}"; do
  name="$(basename "$dir")"
  cp -R "$dir" "$SKILLS_OUT/$name"
  echo "  + skills/$name"
done

# ---------------------------------------------------------------------------
# 2. Per-host transform.
# ---------------------------------------------------------------------------
# Read a single-line quoted frontmatter value from a SKILL.md. e.g.
#   frontmatter_value firetiger-query/SKILL.md user_invocable_description
frontmatter_value() {
  awk -v key="$2" '
    /^---[[:space:]]*$/ { n++; next }
    n==1 {
      if ($0 ~ "^"key":[[:space:]]") {
        sub("^"key":[[:space:]]*", "")
        gsub(/^"|"$/, "")
        print
        exit
      }
    }
  ' "$1"
}

# command name for a skill: strip a leading "firetiger-" (the router skill
# "firetiger" keeps its name).
command_name() {
  case "$1" in
    firetiger) echo firetiger ;;
    firetiger-*) echo "${1#firetiger-}" ;;
    *) echo "$1" ;;
  esac
}

if [ "$HOST" = "claude" ]; then
  CMD_OUT="$TARGET/commands"
  mkdir -p "$CMD_OUT"
  # Remove only the command stubs we previously generated, so hand-authored
  # commands survive but stale managed ones are pruned.
  if [ -d "$CMD_OUT" ]; then
    while IFS= read -r -d '' stale; do
      rm -f "$stale"
    done < <(grep -rlZ "$GEN_MARKER" "$CMD_OUT" 2>/dev/null || true)
  fi

  for dir in "${SKILL_DIRS[@]}"; do
    skill="$(basename "$dir")"
    cmd="$(command_name "$skill")"
    desc="$(frontmatter_value "$dir/SKILL.md" user_invocable_description)"
    [ -n "$desc" ] || desc="Run the Firetiger ${skill} skill"
    cat >"$CMD_OUT/$cmd.md" <<EOF
---
description: ${desc}
user-invocable: true
---

<!-- ${GEN_MARKER} (${TAG}). Do not edit — change the skill upstream. -->

Use the \`${skill}\` skill to help the user with this request. The skill body is
vendored under \`skills/${skill}/\` and is the single source of truth; this
command is only a thin entry point.
EOF
    echo "  + commands/$cmd.md -> $skill"
  done
fi

# ---------------------------------------------------------------------------
# 3. Install the drift-check workflow into the consumer.
# ---------------------------------------------------------------------------
WF_OUT="$TARGET/.github/workflows"
mkdir -p "$WF_OUT"
cp "$SCRIPT_DIR/templates/consumer-drift-check.yml" "$WF_OUT/firetiger-skills-drift.yml"
echo "  + .github/workflows/firetiger-skills-drift.yml"

# ---------------------------------------------------------------------------
# 4. Stamp the vendored copy with the source tag + content hash.
# ---------------------------------------------------------------------------
HASH="$("$SCRIPT_DIR/skills-hash.sh" "$SKILLS_OUT")"
cat >"$SKILLS_OUT/$STAMP_NAME" <<EOF
# ${GEN_MARKER}. Do not edit by hand.
# Update by merging the sync PR from ${SOURCE_REPO}, not by editing skills here.
source=${SOURCE_REPO}
tag=${TAG}
hash=${HASH}
EOF
echo "  + skills/$STAMP_NAME (hash=${HASH})"

echo "Done. Vendored ${SOURCE_REPO}@${TAG} into ${TARGET}."
