#!/usr/bin/env bash
#
# sync-skills.sh — vendor this repo's canonical Firetiger skills into a consumer
# plugin's skills/ directory.
#
# Skills are authored ONCE in this repo (one top-level directory per skill, each
# holding a SKILL.md and optional references/). Both consumer plugins now use the
# IDENTICAL skills/ layout, so the sync is the same for both:
#
#   cursor-plugin   skills -> <target>/skills/   (.cursor-plugin/plugin.json "skills": "skills")
#   claude-plugin   skills -> <target>/skills/   (Claude Code auto-discovers skills/)
#
# It also installs a drift-check workflow and stamps the vendored copy with the
# source tag + content hash (skills/.firetiger-skills-source) so a hand-edited
# vendored copy can't silently diverge from canonical.
#
# --migrate-skills-only performs claude-plugin's ONE-TIME retirement of the old
# command-based layout: if the target still has a commands/ directory, it is
# deleted, the plugin version is bumped, and the README is updated to reflect
# skills-only. Guarded by commands/ presence, so it runs once and is a no-op on
# every later sync.
#
# Usage:
#   sync-skills.sh --target <dir> [--tag <tag>] [--source <dir>]
#                  [--migrate-skills-only] [--dry-run]
#
# --dry-run (-n) mutates a throwaway copy and prints the diff; the real target
# is never written to.
#
# Run locally against a plugin checkout to test, e.g.:
#   scripts/sync-skills.sh --target ../cursor-plugin --tag v1.2.3 --dry-run
#   scripts/sync-skills.sh --target ../claude-plugin --tag v1.2.3 --migrate-skills-only
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE_REPO="firetiger-oss/skills"
STAMP_NAME=".firetiger-skills-source"
GEN_MARKER="Generated by scripts/sync-skills.sh from ${SOURCE_REPO}"

TARGET=""
TAG=""
MIGRATE=0
DRYRUN=0

die() { echo "sync-skills.sh: $*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --target)             TARGET="${2:?}"; shift 2 ;;
    --tag)                TAG="${2:?}"; shift 2 ;;
    --source)             SOURCE_DIR="$(cd "${2:?}" && pwd)"; shift 2 ;;
    --migrate-skills-only) MIGRATE=1; shift ;;
    --dry-run|-n)         DRYRUN=1; shift ;;
    -h|--help)            sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[ -n "$TARGET" ] || die "missing --target <dir>"
[ -d "$TARGET" ] || die "target is not a directory: $TARGET"
TARGET="$(cd "$TARGET" && pwd)"

# --dry-run: work on throwaway copies and diff them at the end. The real target
# is never touched. We keep TWO .git-free copies — a pristine "before" (DRY_BASE)
# and the mutated "after" (DRY_TMP) — so the diff doesn't show .git churn.
ORIG_TARGET=""
DRY_BASE=""
DRY_TMP=""
if [ "$DRYRUN" -eq 1 ]; then
  ORIG_TARGET="$TARGET"
  DRY_BASE="$(mktemp -d)"
  DRY_TMP="$(mktemp -d)"
  trap 'rm -rf "$DRY_BASE" "$DRY_TMP"' EXIT
  cp -R "$ORIG_TARGET/." "$DRY_BASE/"
  rm -rf "$DRY_BASE/.git"           # exclude VCS metadata from the comparison
  cp -R "$DRY_BASE/." "$DRY_TMP/"   # the copy the sync will mutate
  TARGET="$DRY_TMP"
  echo "DRY RUN — no changes will be written to $ORIG_TARGET"
fi

# Default the tag to whatever git can tell us about the source checkout.
if [ -z "$TAG" ]; then
  TAG="$(git -C "$SOURCE_DIR" describe --tags --always --dirty 2>/dev/null || echo dev)"
fi

# Discover canonical skill directories (top-level dirs holding a SKILL.md).
# (Plain while-read loop for bash 3.2 portability — no mapfile.)
SKILL_DIRS=()
while IFS= read -r _dir; do
  [ -n "$_dir" ] && SKILL_DIRS+=("$_dir")
done < <(
  find "$SOURCE_DIR" -mindepth 2 -maxdepth 2 -name SKILL.md -type f \
    | sed "s|/SKILL.md$||" | LC_ALL=C sort
)
[ "${#SKILL_DIRS[@]}" -gt 0 ] || die "no canonical skills (dirs with SKILL.md) found under $SOURCE_DIR"

echo "Syncing ${#SKILL_DIRS[@]} skill(s) from ${SOURCE_REPO}@${TAG} -> ${TARGET}"

# ---------------------------------------------------------------------------
# Helpers for the one-time skills-only migration.
# ---------------------------------------------------------------------------
# Read a single-line quoted frontmatter value from a SKILL.md.
frontmatter_value() {
  awk -v key="$2" '
    /^---[[:space:]]*$/ { n++; next }
    n==1 {
      if ($0 ~ "^"key":[[:space:]]") {
        sub("^"key":[[:space:]]*", "")
        gsub(/^"|"$/, "")
        print
        exit
      }
    }
  ' "$1"
}

# Bump the minor version (X.Y.Z -> X.(Y+1).0) in a plugin manifest.
bump_plugin_version() {
  local f="$1" cur major minor new tmp
  [ -f "$f" ] || { echo "  ! no manifest at $f — skipping version bump" >&2; return 0; }
  cur="$(grep -oE '"version"[[:space:]]*:[[:space:]]*"[0-9]+\.[0-9]+\.[0-9]+"' "$f" \
         | head -n1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || true)"
  [ -n "$cur" ] || { echo "  ! no semver version in $f — skipping bump" >&2; return 0; }
  major="${cur%%.*}"
  minor="$(echo "$cur" | cut -d. -f2)"
  new="${major}.$((minor + 1)).0"
  tmp="$(mktemp)"
  sed -E "s/(\"version\"[[:space:]]*:[[:space:]]*\")${cur//./\\.}(\")/\1${new}\2/" "$f" >"$tmp" && mv "$tmp" "$f"
  echo "  ~ ${f##*/} version ${cur} -> ${new}"
}

# Generate the README skills table from the canonical skills.
build_skills_table() {
  local dir name desc
  printf '### Skills\n\n'
  printf 'Skills are vendored from [`%s`](https://github.com/%s) — do not edit them here.\n\n' "$SOURCE_REPO" "$SOURCE_REPO"
  printf '| Skill | Description |\n|-------|-------------|\n'
  for dir in "${SKILL_DIRS[@]}"; do
    name="$(basename "$dir")"
    desc="$(frontmatter_value "$dir/SKILL.md" user_invocable_description)"
    [ -n "$desc" ] || desc="$(frontmatter_value "$dir/SKILL.md" description)"
    printf '| `%s` | %s |\n' "$name" "$desc"
  done
}

# Rewrite a plugin README for the skills-only layout: fix the layout bullet and
# regenerate the "### Skills" table.
rewrite_readme() {
  local f="$1" tablefile tmp
  [ -f "$f" ] || { echo "  ! no README at $f — skipping" >&2; return 0; }
  # Pass the multi-line table via a file (BSD awk can't take newlines in -v).
  tablefile="$(mktemp)"
  build_skills_table >"$tablefile"
  tmp="$(mktemp)"
  awk -v tablefile="$tablefile" '
    /^- `commands\// {
      print "- `skills/`: Firetiger skills, vendored from firetiger-oss/skills (do not edit here)"
      next
    }
    /^### Skills[[:space:]]*$/ {
      while ((getline line < tablefile) > 0) print line
      close(tablefile)
      inskills = 1
      next
    }
    inskills == 1 {
      if ($0 ~ /^## /) { inskills = 0; print ""; print $0 }
      next
    }
    { print }
  ' "$f" >"$tmp" && mv "$tmp" "$f"
  rm -f "$tablefile"
  echo "  ~ ${f##*/} updated (skills-only)"
}

# ---------------------------------------------------------------------------
# 1. Vendor the skills: wipe and repopulate <target>/skills/ verbatim.
# ---------------------------------------------------------------------------
SKILLS_OUT="$TARGET/skills"
rm -rf "$SKILLS_OUT"
mkdir -p "$SKILLS_OUT"
for dir in "${SKILL_DIRS[@]}"; do
  name="$(basename "$dir")"
  cp -R "$dir" "$SKILLS_OUT/$name"
  echo "  + skills/$name"
done

# ---------------------------------------------------------------------------
# 2. One-time skills-only migration (claude-plugin retiring commands/).
# ---------------------------------------------------------------------------
if [ "$MIGRATE" -eq 1 ] && [ -d "$TARGET/commands" ]; then
  echo "  migrate: retiring command-based layout (skills-only)"
  rm -rf "$TARGET/commands"
  echo "  - commands/ (deleted)"
  bump_plugin_version "$TARGET/.claude-plugin/plugin.json"
  rewrite_readme "$TARGET/README.md"
fi

# ---------------------------------------------------------------------------
# 3. Install the drift-check workflow into the consumer.
# ---------------------------------------------------------------------------
WF_OUT="$TARGET/.github/workflows"
mkdir -p "$WF_OUT"
cp "$SCRIPT_DIR/templates/consumer-drift-check.yml" "$WF_OUT/firetiger-skills-drift.yml"
echo "  + .github/workflows/firetiger-skills-drift.yml"

# ---------------------------------------------------------------------------
# 4. Stamp the vendored copy with the source tag + content hash.
# ---------------------------------------------------------------------------
HASH="$("$SCRIPT_DIR/skills-hash.sh" "$SKILLS_OUT")"
cat >"$SKILLS_OUT/$STAMP_NAME" <<EOF
# ${GEN_MARKER}. Do not edit by hand.
# Update by merging the sync PR from ${SOURCE_REPO}, not by editing skills here.
source=${SOURCE_REPO}
tag=${TAG}
hash=${HASH}
EOF
echo "  + skills/$STAMP_NAME (hash=${HASH})"

if [ "$DRYRUN" -eq 1 ]; then
  echo
  echo "=== DRY RUN: changes that WOULD be applied to ${ORIG_TARGET} ==="
  # Compare the pristine (before) and mutated (after) .git-free copies.
  # Prefer git for readable, colored output; fall back to plain diff.
  if command -v git >/dev/null 2>&1; then
    git --no-pager diff --no-index --stat -- "$DRY_BASE" "$DRY_TMP" 2>/dev/null || true
    echo
    git --no-pager diff --no-index -- "$DRY_BASE" "$DRY_TMP" 2>/dev/null || true
  else
    diff -ruN "$DRY_BASE" "$DRY_TMP" || true
  fi
  echo "=== end dry run (nothing was written to ${ORIG_TARGET}) ==="
else
  echo "Done. Vendored ${SOURCE_REPO}@${TAG} into ${TARGET}."
fi
